[versions]
androidGradlePlugin = "8.5.0"
compileSdk = "34"
targetSdk = "34"
minSdk21 = "21"
minSdk28 = "28"
ndkVersion = "26.1.10909125"
cmakeVersion = "3.22.1"
jvmTarget = "17"
versionCode = "1"
versionName = "1.0"
kotlin = "2.0.0"
kspVersion = "2.0.0-1.0.22"
kotlinpoet = "1.17.0"
proguardGradle = "7.5.0"
junit = "4.13.2"

core = "0.2.7"
glide = "4.16.0"
gson = "2.10.1"
hiddenapibypass = "4.3"
lifecycleExtensions = "2.2.0"
lifecycleLivedataKtx = "2.4.0"
lifecycleViewmodelKtx = "2.4.0"
retrofit = "2.11.0"
rxandroid = "3.0.2"
rxjava = "3.1.8"
swiperefreshlayout = "1.1.0"
symbolProcessingApi = "2.0.0-1.0.22"
eventbus = "3.3.1"
logger = "2.2.0"

androidxCore = "1.12.0"
androidxStartup = "1.1.1"
androidxMultidex = "2.0.1"
androidxAppCompat = "1.6.1"
googleMaterial = "1.11.0"
androidxConstraintlayout = "2.1.4"
androidxVectordrawable = "1.1.0"
androidxLifecycle = "2.7.0"
androidxNavigation = "2.7.6"

androidxJunit = "1.1.5"
androidxEspresso = "3.5.1"
annotation = "1.7.1"
slice-builders = "1.0.0"

pine-core = "0.2.9"
pine-xposed = "0.0.9"
pine-enhances = "0.0.3"
workRuntime = "2.9.0"
activity = "1.8.0"
webkit = "1.11.0"

[libraries]
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-livedata-ktx-v240 = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-ktx-v240 = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidxStartup" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "androidxMultidex" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "androidxVectordrawable" }
androidx-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguardGradle" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "eventbus" }
eventbus-annotation = { group = "org.greenrobot", name = "eventbus-annotation-processor", version.ref = "eventbus" }
logger = { group = "com.orhanobut", name = "logger", version.ref = "logger" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
slice-builders = { group = "androidx.slice", name = "slice-builders", version.ref = "slice-builders" }
pine-core = { module = "top.canyie.pine:core", version.ref = "pine-core" }
pine-xposed = { module = "top.canyie.pine:xposed", version.ref = "pine-xposed" }
pine-enhances = { module = "top.canyie.pine:enhances", version.ref = "pine-enhances" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbolProcessingApi" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }